#!/usr/bin/env sh

# Load Husky
. "$(dirname -- "$0")/_/husky.sh"

# Load commit message
message="$(cat "$1")"

# Perform spell check using TextGears API
response=$(echo "$message" | curl -sS -X POST -H "Content-Type: application/json" --data-binary @- https://api.textgears.com/check.php?text="@")
errors=$(echo "$response" | sed -n 's/.*"bad":"\([^"]*\)".*/\1/p')

if [ -z "$errors" ]; then
  echo "✅ Spell check passed!"
  exit 0
else
  echo "🚨 Spell check failed! 😕"
  echo "Your commit message contains spelling mistakes:"
  echo "$errors"
  exit 1
fi
